spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_subscription_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    default-schema: public
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.springframework: INFO
    com.example.userservice: DEBUG